obj={}
app=require("express")()
net=require("http").createServer(app)
app.get("/",(req,res)=>{
res.sendFile(__dirname+"/public/index.htm")
})
app.use("/public",require("express").static(__dirname+"/public"))
net.listen(process.env.PORT||3000,()=>{console.log("Ready!")})
require("socket.io")(net,{}).sockets.on("connection",(socket)=>{
  socket.i=Math.random()
  obj[socket.i]={x:0,y:0,z:0}
  setInterval(()=>{
    socket.emit("msg",{script:'draw('+socket.id+','+obj[socket.i].x+','+obj[socket.i].y+','+obj[socket.i].z+')'})
    socket.emit("msg",{script:'camera.position.set('+obj[socket.i].x+','+obj[socket.i].y+','+eval(obj[socket.i].z+5)+')'})
  },1)
})
