app=require("express")()
net=require("http").createServer(app)
app.get("/",(req,res)=>{
res.sendFile(__dirname+"/public/index.htm")
})
app.use("/public",require("express").static(__dirname+"/public"))
net.listen(process.env.PORT||3000,()=>{console.log("Ready!")})
require("socket.io")(net,{}).sockets.on("connection",(socket)=>{
  setInterval(()=>{
    socket.emit("msg",{script:'draw(0,0,0,0)'})
    socket.emit("msg",{script:'camera.position.set(0,0,5)'})
  },1)
})
